<a href="https://colab.research.google.com/github/pattichis/AI4All-Med/blob/main/Session_3_1_Linear_Layer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Layers

## Goals

1. Explore the use of linear layers.
2. Define your own linear layer.
3. Explore inputs and outputs for a custom linear layer.

# Define a linear layer manually

Study the code and answer:
1. Where are the neuron weights stored?
2. Where are the biases stored?
3. How do you set the input?

In [ ]:
import torch
import torch.nn as nn

# 1. Create a Linear layer with known dimensions
linear_layer = nn.Linear(in_features=3, out_features=2)

# 2. Manually set weights and bias for full transparency
# Weight shape: (out_features, in_features) => (2, 3)
custom_weight = torch.tensor([[1.0, 2.0, 3.0],     # First output neuron
                              [4.0, 5.0, 6.0]])    # Second output neuron
custom_bias = torch.tensor([0.5, -0.5])            # One bias per output neuron

# Apply custom weights and biases
with torch.no_grad():
    linear_layer.weight.copy_(custom_weight)
    linear_layer.bias.copy_(custom_bias)

# 3. Define a custom input: shape (batch_size=1, in_features=3)
input_tensor = torch.tensor([[1.0, 0.0, -1.0]])  # A single input vector

# 4. Pass the input through the linear layer
output = linear_layer(input_tensor)

# 5. Print everything clearly
print("Input:")
print(input_tensor)
print("\nWeight matrix:")
print(linear_layer.weight)
print("\nBias:")
print(linear_layer.bias)
print("\nOutput:")
print(output)


Input:
tensor([[ 1.,  0., -1.]])

Weight matrix:
Parameter containing:
tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

Bias:
Parameter containing:
tensor([ 0.5000, -0.5000], requires_grad=True)

Output:
tensor([[-1.5000, -2.5000]], grad_fn=<AddmmBackward0>)


The first pixel is calculated using:
$$
\text{Input patch} =
\begin{bmatrix}
 1 & 0 & -1
\end{bmatrix}
\quad
\text{Neuron 1 weights} =
\begin{bmatrix}
1 & 2 & 3
\end{bmatrix}
\quad\text{Bias for Neuron 1}=0.5
$$


Multiply corresponding values and add bias:
$$
\begin{aligned}
\text{Neuron 1 output} &=
         (1 \times 1) + (0 \times 2) + (-1 \times 3) + 0.5 \\
&= 1 -3 + 0.5  \\
&= -1.5
\end{aligned}
$$


# Enter your work below

# Set your own linear layer

Experiment with the linear layer as follows:
1. Modify the weights of neuron 1 to compute an average using 1/3 for all weights. Apply and write down the results.
2. What happens when the input is all zeros? Explain.
3. Modify the weights of neuron 2 to select the middle pixel using [0, 1, 0].
4. Add an additional neuron with weights. Share what tou chose to do.

In [ ]:
import torch
import torch.nn as nn

# 1. Create a Linear layer with known dimensions
linear_layer = nn.Linear(in_features=3, out_features=2)

# 2. Manually set weights and bias for full transparency
# Weight shape: (out_features, in_features) => (2, 3)
custom_weight = torch.tensor([[1.0, 2.0, 3.0],     # First output neuron
                              [4.0, 5.0, 6.0]])    # Second output neuron
custom_bias = torch.tensor([0.5, -0.5])            # One bias per output neuron

# Apply custom weights and biases
with torch.no_grad():
    linear_layer.weight.copy_(custom_weight)
    linear_layer.bias.copy_(custom_bias)

# 3. Define a custom input: shape (batch_size=1, in_features=3)
input_tensor = torch.tensor([[1.0, 0.0, -1.0]])  # A single input vector

# 4. Pass the input through the linear layer
output = linear_layer(input_tensor)

# 5. Print everything clearly
print("Input:")
print(input_tensor)
print("\nWeight matrix:")
print(linear_layer.weight)
print("\nBias:")
print(linear_layer.bias)
print("\nOutput:")
print(output)


Input:
tensor([[ 1.,  0., -1.]])

Weight matrix:
Parameter containing:
tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

Bias:
Parameter containing:
tensor([ 0.5000, -0.5000], requires_grad=True)

Output:
tensor([[-1.5000, -2.5000]], grad_fn=<AddmmBackward0>)
